name = "GAMS"
uuid = "1ca51c6a-1b4d-4546-9ae1-53e0a243ab12"
authors = ["GAMS Software GmbH <support@gams.com>"]
version = "0.2.3"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
MathOptInterface = "~0.9.13"
julia = "^1.2"
